spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create

amazon:
  dynamodb:
    endpoint: http://localhost:4598
    region: local
    accesskey: accessKeyTest
    secretkey: secretKeyTest
    tablename-suffix: -local
  sqs:
    endpoint: http://localhost:4566
    region: us-west-2
    queue: knight-path-queue